services:
  postgres:
    image: postgres:15

    environment:
      POSTGRES_DB: bookease
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/migrations.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:3
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - '8080:80'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bookease
      DB_USER: postgres
      DB_PASS: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: change-this-to-a-long-random-string-in-production
      JWT_TTL: 86400
      APP_ENV: development
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
